name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Execute deploy script
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: cd /var/www/squirrelcontrol && sh deploy.sh
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSPHRASE }}
        env:
          CI: true
